name 'helloworld'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures helloworld'
long_description 'Installs/Configures helloworld'
version '0.1.0'
