name    'nu113r-snoopy'
version '0.1.0'
source 'UNKNOWN'
author 'nu113r'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
#dependency 'lwf/remote_file', '>= 1.1.3'
