Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "docker-ubuntu-host-normal-linking"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end
	config.vm.provision "shell", inline: <<-SHELL
		apt-get -y update
		apt-get -y install docker.io
		service docker stop
		usermod -a -G docker vagrant
		service docker start
	SHELL

end
