name 'configurenginx'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures configurenginx'
long_description 'Installs/Configures configurenginx'
version '0.1.0'
