Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "docker-ubuntu-host-compose"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "3096"
	end
	config.vm.provision "file", source: "docker.list", destination: "/tmp/docker.list"
	config.vm.provision "shell", inline: <<-SHELL
		cp /tmp/docker.list /etc/apt/sources.list.d/docker.list
		apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
		apt-get -y update
		apt-get -y purge lxc-docker
		apt-cache policy docker-engine
		apt-get -y update	
		apt-get -y install docker-engine
		usermod -a -G docker vagrant
		service docker stop
		service docker start
		curl -L https://github.com/docker/compose/releases/download/1.5.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
		chmod +x /usr/local/bin/docker-compose
				
	SHELL

end
